### ISSUE TITLE
Minimal Gosu code fails.

### ISSUE THREAD

**Issue by zackp30** [ruboto/ruboto#663]
Code:

```ruby
require 'ruboto/widget'
require 'ruboto/util/toast'
require 'gosu'

ruboto_import_widgets :Button, :LinearLayout, :TextView

class GameWindow < Gosu::Window
  def initialize
    super 640, 480, false
    self.caption = "Hai!"
    @background_image = Gosu::Image.new(self, Ruboto::R::drawable::space)
    puts @background_image
  end
  def draw
    @background_image.draw(0, 0)
  end
end


class TestActivity
  def onCreate(bundle)
    super(bundle)
    Gosu::AndroidInitializer.instance.start(self)
    set_title 'Key binder'
  end
  def on_ready
    window = GameWindow.new
    window.show
  rescue Exception => e
    puts "#{ e } (#{ e.class } #{e.message} #{e.backtrace.inspect} )!"
  end
end
```

Stacktrace (it was merged into one line, sorry if it's hard to make use of):
```
I/System.out(14956): undefined method `character_atlas8' for Java::NetApertronTest::R::drawable:Class (NoMethodError undefined method `character_atlas8' for Java::NetApertronTest::R::drawable:Class ["org/jruby/RubyBasicObject.java:1494:in `method_missing'", "file:/data/app/net.apertron.test-1.apk!/ruboto/base.rb:20:in `method_missing'", "file:/data/app/net.apertron.test-1.apk!/gosu_android/graphics/font.rb:11:in `initialize'", "file:/data/app/net.apertron.test-1.apk!/gosu_android/main-window.rb:94:in `initialize'", "jar:file:/data/app/net.apertron.test-1.apk!/test_activity.rb:9:in `initialize'", "jar:file:/data/app/net.apertron.test-1.apk!/test_activity.rb:27:in `on_ready'", "file:/data/app/net.apertron.test-1.apk!/gosu_android/main-window.rb:32:in `on_ready'", "file:/data/app/net.apertron.test-1.apk!/gosu_android/graphics/graphics.rb:207:in `onSurfaceCreated'"] )!
I/System.out(14956): undefined method `draw' for nil:NilClass (NoMethodError undefined method `draw' for nil:NilClass ["org/jruby/RubyBasicObject.java:1494:in `method_missing'", "file:/data/app/net.apertron.test-1.apk!/ruboto/base.rb:20:in `method_missing'", "jar:file:/data/app/net.apertron.test-1.apk!/test_activity.rb:15:in `draw'", "file:/data/app/net.apertron.test-1.apk!/gosu_android/main-window.rb:322:in `do_tick'", "file:/data/app/net.apertron.test-1.apk!/gosu_android/main-window.rb:175:in `do_show'", "file:/data/app/net.apertron.test-1.apk!/gosu_android/graphics/graphics.rb:194:in `onDrawFrame'"] )!
```

**Comment by abdias9** [comment]
I have the same problem.

**Comment by donv** [comment]
Hi @zackp30 and @abdias9 !

I'll be releasing Ruboto 1.3.0 later today.  Could you try it and see if it works for you?

**Comment by zackp30** [comment]
Of course! I'll be happy to help. :smile:

**Comment by ashes999** [comment]
With 1.3.0, I'm getting an exception lodaing Gosu:

`org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- gosu`

Looks like I need to add it to Ruboto somehow, but how?

**Comment by donv** [comment]
Hi all!

Anyone tried this with a newer Ruboto release?

**Comment by ashes999** [comment]
Gosu-Android is a dead project. I wouldn't recommend pursuing this.

**Comment by donv** [comment]
Gosu-Android seems like a worthwhile idea.  Hopefully it can be revived.

@zackp30 maybe you want to contribute to Gosu-Android?

**Comment by ashes999** [comment]
@zackp30 if you plan to take over gosu-android, that's a different story. Their readme clearly states:

> Develoment on the engine has stopped until further notice.

For this reason, I created an alternative called [Terrace](https://github.com/ashes999/terrace), which is a lightweight Ruby wrapper around libGDX. LibGDX is pretty mature, and the wrapping work is pretty simple. It's also a dead project.

That's probably your best bet for running games on top of Ruboto, unless you want to roll your own.

**Comment by zackp30** [comment]
I probably won't be able to, since I have exams coming up.

Sorry. :frowning:

**Comment by donv** [comment]
No problem.  Come back after the exams.  :smile:
