### ISSUE TITLE
Exception running "ruboto setup -t 19 -y" on OS X 10.10

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#702]
Hi!

When running ```ruboto setup -t 19 -y``` on OS X 10.10 I get the following error:

```
F, [2015-03-13T11:46:23.229638 #2795] FATAL -- : invalid byte sequence in UTF-8 (ArgumentError)
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/util/setup.rb:621:in `=~'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/util/setup.rb:621:in `block (2 levels) in update_sdk'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/util/setup.rb:618:in `each_char'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/util/setup.rb:618:in `block in update_sdk'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/util/setup.rb:613:in `popen'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/util/setup.rb:613:in `update_sdk'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/util/setup.rb:557:in `install_android_tools'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/util/setup.rb:267:in `install_all'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/util/setup.rb:23:in `setup_ruboto'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/commands/base.rb:453:in `run'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `block in run'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `catch'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `run'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/lib/ruboto/commands/base.rb:28:in `main'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.0/bin/ruboto:11:in `<top (required)>'
/Users/a1022453/.rvm/gems/ruby-2.2.0/bin/ruboto:23:in `load'
/Users/a1022453/.rvm/gems/ruby-2.2.0/bin/ruboto:23:in `<main>'
/Users/a1022453/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/a1022453/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

I have not tried on other platforms.

**Comment by donv** [comment]
I get the same error with master:

```
F, [2015-03-13T11:49:14.043473 #2838] FATAL -- : invalid byte sequence in UTF-8 (ArgumentError)
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/util/setup.rb:621:in `=~'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/util/setup.rb:621:in `block (2 levels) in update_sdk'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/util/setup.rb:618:in `each_char'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/util/setup.rb:618:in `block in update_sdk'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/util/setup.rb:613:in `popen'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/util/setup.rb:613:in `update_sdk'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/util/setup.rb:557:in `install_android_tools'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/util/setup.rb:267:in `install_all'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/util/setup.rb:23:in `setup_ruboto'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/commands/base.rb:453:in `run'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `block in run'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `catch'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `run'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/lib/ruboto/commands/base.rb:28:in `main'
/Users/a1022453/.rvm/gems/ruby-2.2.0/gems/ruboto-1.2.1.dev/bin/ruboto:11:in `<top (required)>'
/Users/a1022453/.rvm/gems/ruby-2.2.0/bin/ruboto:23:in `load'
/Users/a1022453/.rvm/gems/ruby-2.2.0/bin/ruboto:23:in `<main>'
/Users/a1022453/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/a1022453/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```
