### ISSUE TITLE
Can't detect version - Malformed version number android-4.4.2

### ISSUE THREAD

**Issue by nkts** [ruboto/ruboto#727]
```
$ ruboto setup
WARN: Unresolved specs during Gem::Specification.reset:
      rake (~> 10.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Android SDK Command adb  : Found
F, [2015-05-19T01:29:50.911779 #21743] FATAL -- : Malformed version number string android-4.4.2 (ArgumentError)
/usr/share/rubygems/rubygems/version.rb:202:in `initialize'
/usr/share/rubygems/rubygems/version.rb:192:in `new'
/usr/share/rubygems/rubygems/version.rb:192:in `new'
/home/nkts/.gem/ruby/gems/ruboto-1.3.0/lib/ruboto/util/setup.rb:227:in `block in check_for_build_tools'
/home/nkts/.gem/ruby/gems/ruboto-1.3.0/lib/ruboto/util/setup.rb:227:in `each'
/home/nkts/.gem/ruby/gems/ruboto-1.3.0/lib/ruboto/util/setup.rb:227:in `sort_by'
/home/nkts/.gem/ruby/gems/ruboto-1.3.0/lib/ruboto/util/setup.rb:227:in `check_for_build_tools'
/home/nkts/.gem/ruby/gems/ruboto-1.3.0/lib/ruboto/util/setup.rb:170:in `check_all'
/home/nkts/.gem/ruby/gems/ruboto-1.3.0/lib/ruboto/util/setup.rb:23:in `setup_ruboto'
/home/nkts/.gem/ruby/gems/ruboto-1.3.0/lib/ruboto/commands/base.rb:453:in `run'
/home/nkts/.gem/ruby/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `block in run'
/home/nkts/.gem/ruby/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `catch'
/home/nkts/.gem/ruby/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `run'
/home/nkts/.gem/ruby/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/home/nkts/.gem/ruby/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/home/nkts/.gem/ruby/gems/ruboto-1.3.0/lib/ruboto/commands/base.rb:28:in `main'
/home/nkts/.gem/ruby/gems/ruboto-1.3.0/bin/ruboto:11:in `<top (required)>'
/home/nkts/bin/ruboto:23:in `load'
/home/nkts/bin/ruboto:23:in `<main>'
```

**Comment by Zhomart** [comment]
Ruby version: `=> jruby-1.7.19 [ x86_64 ]` by rvm
OSX: `10.10.4 (14E17e)` Yosemite
Ruboto version: `1.3.1.dev` aba9f243e1d481253de92530b91b4490dcbc3bdc


```
$ ruboto setup -y
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Intel HAXM               : Old   1.1.2/
Android SDK Command adb  : Found
F, [2015-05-19T15:48:20.384000 #33608] FATAL -- : Malformed version number string android-4.4W (ArgumentError)
/Users/zhomart/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/version.rb:206:in `initialize'
/Users/zhomart/.rvm/rubies/jruby-1.7.19/lib/ruby/shared/rubygems/version.rb:198:in `new'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/util/setup.rb:232:in `check_for_build_tools'
org/jruby/RubyArray.java:1613:in `each'
org/jruby/RubyEnumerable.java:503:in `sort_by'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/util/setup.rb:232:in `check_for_build_tools'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/util/setup.rb:170:in `check_all'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/util/setup.rb:23:in `setup_ruboto'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/commands/base.rb:453:in `run'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `run'
org/jruby/RubyKernel.java:1270:in `catch'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/program/class_methods.rb:143:in `run'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/Users/zhomart/.rvm/gems/jruby-1.7.19/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/Users/zhomart/Development/ruboto/ruboto/lib/ruboto/commands/base.rb:28:in `main'
/Users/zhomart/Development/ruboto/ruboto/bin/ruboto:11:in `(root)'
org/jruby/RubyKernel.java:1087:in `load'
/Users/zhomart/.rvm/gems/jruby-1.7.19/bin/ruboto:1:in `(root)'
org/jruby/RubyKernel.java:1107:in `eval'
/Users/zhomart/.rvm/gems/jruby-1.7.19/bin/jruby_executable_hooks:15:in `(root)'
```

**Comment by danielpassos** [comment]
Hi @nkts @Zhomart Was it fixed?

**Comment by danielpassos** [comment]
@Zhomart Could you send the result of `android list target`?

**Comment by Zhomart** [comment]
@danielpassos Here it is https://gist.github.com/Zhomart/8dc4ac4988224ca7ed14

**Comment by donv** [comment]
Looks like we need to be even more flexible when recognising Android platform version.

@danielpassos you on it?

**Comment by danielpassos** [comment]
@donv yes I'm on it

**Comment by donv** [comment]
Hi @danielpassos !

How is this coming along?
