### ISSUE TITLE
Fix OpenSSL

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#793]
After fixing #726 , we get this:

```
01-27 11:44:44.230  6283  6301 I System.out: Exception in Thread with large stack: load error: jopenssl/load -- java.lang.ExceptionInInitializerError: null
01-27 11:44:44.230  6283  6301 I System.out: org/jruby/RubyKernel.java:1040:in `require'
01-27 11:44:44.230  6283  6301 I System.out: /data/app/org.ruboto.test_app-2/base.apk!/jruby.home/lib/ruby/shared/openssl.rb:1:in `(root)'
01-27 11:44:44.230  6283  6301 I System.out: org/jruby/RubyKernel.java:1040:in `require'
01-27 11:44:44.230  6283  6301 I System.out: /data/app/org.ruboto.test_app-2/base.apk!/jruby.home/lib/ruby/1.9/net/https.rb:1:in `(root)'
01-27 11:44:44.230  6283  6301 I System.out: org/jruby/RubyKernel.java:1040:in `require'
01-27 11:44:44.230  6283  6301 I System.out: /data/app/org.ruboto.test_app-2/base.apk!/jruby.home/lib/ruby/1.9/net/https.rb:22:in `(root)'
01-27 11:44:44.230  6283  6301 I System.out: org/jruby/RubyProc.java:281:in `call'
01-27 11:44:44.230  6283  6301 I System.out: jar:file:/data/app/org.ruboto.test_app-2/base.apk!/ssl_activity.rb:1:in `(root)'
01-27 11:44:44.230  6283  6301 I System.out: org/jruby/RubyKernel.java:1040:in `require'
01-27 11:44:44.230  6283  6301 I System.out: /data/app/org.ruboto.test_app-2/base.apk!/jruby.home/lib/ruby/shared/openssl.rb:1:in `(root)'
01-27 11:44:44.230  6283  6301 I System.out: org/jruby/RubyKernel.java:1040:in `require'
01-27 11:44:44.230  6283  6301 I System.out: /data/app/org.ruboto.test_app-2/base.apk!/jruby.home/lib/ruby/1.9/net/https.rb:1:in `(root)'
01-27 11:44:44.230  6283  6301 I System.out: org/jruby/RubyKernel.java:1040:in `require'
01-27 11:44:44.230  6283  6301 I System.out: /data/app/org.ruboto.test_app-2/base.apk!/jruby.home/lib/ruby/1.9/net/https.rb:22:in `(root)'
01-27 11:44:44.230  6283  6301 I System.out: org/jruby/RubyProc.java:281:in `call'
01-27 11:44:44.230  6283  6301 I System.out: jar:file:/data/app/org.ruboto.test_app-2/base.apk!/ssl_activity.rb:1:in `(root)'
0
```

**Comment by donv** [comment]
Looks like this may be the cause:

```
01-27 12:13:10.090  6914  6932 W System.err: Caused by: java.lang.StringIndexOutOfBoundsException: length=1; regionStart=0; regionLength=3
01-27 12:13:10.100  6914  6932 W System.err: 	at java.lang.String.startEndAndLength(String.java:298)
01-27 12:13:10.100  6914  6932 W System.err: 	at java.lang.String.substring(String.java:1087)
01-27 12:13:10.100  6914  6932 W System.err: 	at org.jruby.ext.openssl.OpenSSL.javaVersion8(OpenSSL.java:277)
01-27 12:13:10.100  6914  6932 W System.err: 	at org.jruby.ext.openssl.SSL.configureJSSE(SSL.java:77)
01-27 12:13:10.100  6914  6932 W System.err: 	at org.jruby.ext.openssl.SSL.<clinit>(SSL.java:74)
```

**Comment by donv** [comment]
Got a patch upstream:  https://github.com/jruby/jruby-openssl/commit/00dbb23937e468ef0d83456e53b87ea3e47766b2

Should be in JRuby 1.7.25.
