### ISSUE TITLE
java.lang.UnsupportedOperationException: can't load this type of class file

### ISSUE THREAD

**Issue by javalovercn** [ruboto/ruboto#802]
```
def connect
	puts "before getCtx"
	@ctx = getProjectContext()
	puts "suc getCtx"
	@device = self
	puts "set device"
	@ctx.run {
		while @isDisconn == false do
			msg = @device.getFreeMessage(@refDev)
			temp = Java::java.util.Random.new()
			msg.setStringBody("temperature", String.valueOf(temp.nextInt(20)))
			@device.dispatch(msg, true)
				
			Thread.sleep(3000)
		end
		puts "done runnable (["+@refDev+"].connect())"
	}
	puts "Device ["+@refDev+"] connect successful!"
	return [@refDev]
end
```
it runs on ruboto_core_1_0_5.apk, apk is loaded by DexClassLoader, prints as following
```
04-23 14:46:29.449: I/System.out(10269): before getCtx
04-23 14:46:29.469: I/System.out(10269): suc getCtx
04-23 14:46:29.469: I/System.out(10269): set device
04-23 14:46:29.482: W/System.err(10269): java.lang.UnsupportedOperationException: can't load this type of class file
04-23 14:46:29.483: W/System.err(10269): 	at java.lang.ClassLoader.defineClass(ClassLoader.java:300)
04-23 14:46:29.483: W/System.err(10269): 	at org.jruby.util.JRubyClassLoader.defineClass(JRubyClassLoader.java:173)
04-23 14:46:29.483: W/System.err(10269): 	at org.jruby.java.codegen.RealClassGenerator.defineOldStyleImplClass(RealClassGenerator.java:244)
04-23 14:46:29.483: W/System.err(10269): 	at org.jruby.java.codegen.RealClassGenerator.createOldStyleImplClass(RealClassGenerator.java:63)
04-23 14:46:29.483: W/System.err(10269): 	at org.jruby.javasupport.Java.newInterfaceImpl(Java.java:1183)
04-23 14:46:29.483: W/System.err(10269): 	at org.jruby.java.proxies.JavaInterfaceTemplate.jcreateProxy(JavaInterfaceTemplate.java:281)
04-23 14:46:29.483: W/System.err(10269): 	at org.jruby.java.proxies.JavaInterfaceTemplate.access$000(JavaInterfaceTemplate.java:30)
04-23 14:46:29.483: W/System.err(10269): 	at org.jruby.java.proxies.JavaInterfaceTemplate$4.call(JavaInterfaceTemplate.java:181)
04-23 14:46:29.483: W/System.err(10269): 	at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodN.call(JavaMethod.java:661)
04-23 14:46:29.483: W/System.err(10269): 	at org.jruby.internal.runtime.methods.DynamicMethod.call(DynamicMethod.java:198)
04-23 14:46:29.483: W/System.err(10269): 	at org.jruby.RubyClass.finvoke(RubyClass.java:624)
```

it seems that there is error on **@ctx.run{}**, what should I do now?

other option information is done for ruboto as follow : 
1. System.setProperty("jruby.ji.proxyClassFactory", "org.ruboto.DalvikProxyClassFactory");
2. System.setProperty("jruby.class.cache.path", proxyCache.getAbsolutePath());
3. container.setCompatVersion(org.jruby.CompatVersion.RUBY2_0);
4. container.setCompileMode(org.jruby.RubyInstanceConfig$CompileMode.JIT);

**Comment by javalovercn** [comment]
read and copy some codes from JRubyAdapter.setUpJRuby(Context appContext), and it works well now.
```
System.setProperty("jruby.backtrace.style", "normal"); // normal raw full mri
System.setProperty("jruby.bytecode.version", "1.6");
// BEGIN Ruboto RubyVersion
// System.setProperty("jruby.compat.version", "RUBY2_0"); // RUBY1_9 is the default in JRuby 1.7
// END Ruboto RubyVersion
// System.setProperty("jruby.compile.backend", "DALVIK");
System.setProperty("jruby.compile.mode", "OFF"); // OFF OFFIR JITIR? FORCE FORCEIR
System.setProperty("jruby.interfaces.useProxy", "true");
System.setProperty("jruby.ir.passes", "LocalOptimizationPass,DeadCodeElimination");
System.setProperty("jruby.management.enabled", "false");
System.setProperty("jruby.native.enabled", "false");
System.setProperty("jruby.objectspace.enabled", "false");
System.setProperty("jruby.rewrite.java.trace", "true");
System.setProperty("jruby.thread.pooling", "true");

// Used to enable JRuby to generate proxy classes
System.setProperty("jruby.ji.proxyClassFactory", "org.ruboto.DalvikProxyClassFactory");
System.setProperty("jruby.ji.upper.case.package.name.allowed", "true");
System.setProperty("jruby.class.cache.path", appContext.getDir("dex", 0).getAbsolutePath());
System.setProperty("java.io.tmpdir", appContext.getCacheDir().getAbsolutePath());

final String jrubyHome = (jrubyVersion.startsWith("9.0.0.0") ?
                        "jar:" : "file:") + apkName + "!/jruby.home";
                // EMXIF

Log.i("Setting JRUBY_HOME: " + jrubyHome);
// This needs to be set before the ScriptingContainer is initialized
System.setProperty("jruby.home", jrubyHome);

//////////////////////////////////
//
// Disable rubygems
//
Class rubyClass = Class.forName("org.jruby.Ruby", true, scriptingContainerClass.getClassLoader());
Class rubyInstanceConfigClass = Class.forName("org.jruby.RubyInstanceConfig", true, scriptingContainerClass.getClassLoader());

Object config = rubyInstanceConfigClass.getConstructor().newInstance();
rubyInstanceConfigClass.getMethod("setDisableGems", boolean.class).invoke(config, true);
rubyInstanceConfigClass.getMethod("setLoader", ClassLoader.class).invoke(config, classLoader);


// This will become the global runtime and be used by our ScriptingContainer
rubyClass.getMethod("newInstance", rubyInstanceConfigClass).invoke(null, config);
```

**Comment by donv** [comment]
@javalovercn Glad to hear you solved it!
