### ISSUE TITLE
(NoMethodError) undefined method `current' for Java::JavaLang::Thread:Class

### ISSUE THREAD

**Issue by javalovercn** [ruboto/ruboto#803]
```
04-24 09:42:10.863: W/System.err(9686): java.lang.reflect.InvocationTargetException
04-24 09:42:10.863: W/System.err(9686): 	at java.lang.reflect.Method.invoke(Native Method)
04-24 09:42:10.863: W/System.err(9686): 	at java.lang.reflect.Method.invoke(Method.java:372)
04-24 09:42:10.863: W/System.err(9686): 	at hc.util.ClassUtil.invokeWithExceptionOut(ClassUtil.java:95)
04-24 09:42:10.863: W/System.err(9686): 	at hc.server.ui.design.engine.HCJRubyEngine.runScriptlet(HCJRubyEngine.java:136)
04-24 09:42:10.863: W/System.err(9686): 	at hc.server.ui.design.hpj.RubyExector.runNoWait(RubyExector.java:121)
04-24 09:42:10.863: W/System.err(9686): 	at hc.server.ui.design.hpj.RubyExector$2.run(RubyExector.java:49)
04-24 09:42:10.863: W/System.err(9686): 	at hc.core.util.ThreadPool$1.run(ThreadPool.java:45)
04-24 09:42:10.863: W/System.err(9686): 	at hc.core.util.RecycleThread.run(RecycleThread.java:27)
04-24 09:42:10.863: W/System.err(9686): 	at java.lang.Thread.run(Thread.java:818)
04-24 09:42:10.863: W/System.err(9686): Caused by: org.jruby.embed.EvalFailedException: (NoMethodError) undefined method `current' for Java::JavaLang::Thread:Class
04-24 09:42:10.863: W/System.err(9686): 	at org.jruby.embed.internal.EmbedEvalUnitImpl.run(EmbedEvalUnitImpl.java:133)
04-24 09:42:10.863: W/System.err(9686): 	... 9 more
04-24 09:42:10.863: W/System.err(9686): Caused by: org.jruby.exceptions.RaiseException: (NoMethodError) undefined method `current' for Java::JavaLang::Thread:Class
04-24 09:42:10.863: W/System.err(9686): 	at RUBY.mon_enter(/data/data/homecenter.mobi.server/files/jruby.jar.apk!/jruby.home/lib/ruby/2.0/monitor.rb:184)
04-24 09:42:10.863: W/System.err(9686): 	at RUBY.require(/data/data/homecenter.mobi.server/files/jruby.jar.apk!/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:39)
04-24 09:42:10.863: W/System.err(9686): 	at RUBY.(root)(<MyConverter>:5)
04-24 09:42:10.863: W/System.err(9686): ------------------error on JRuby script : io/console on JRuby shells out to stty for most operations
04-24 09:42:10.863: W/System.err(9686): file:/data/data/homecenter.mobi.server/files/jruby.jar.apk!/jruby/java/core_ext/object.rb:73 warning: already initialized constant Thread
04-24 09:42:10.863: W/System.err(9686): file:/data/data/homecenter.mobi.server/files/jruby.jar.apk!/jruby/java/core_ext/object.rb:73 warning: already initialized constant String
04-24 09:42:10.863: W/System.err(9686): NoMethodError: undefined method `current' for Java::JavaLang::Thread:Class
04-24 09:42:10.863: W/System.err(9686):   mon_enter at /data/data/homecenter.mobi.server/files/jruby.jar.apk!/jruby.home/lib/ruby/2.0/monitor.rb:184
04-24 09:42:10.863: W/System.err(9686):     require at /data/data/homecenter.mobi.server/files/jruby.jar.apk!/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:39
04-24 09:42:10.863: W/System.err(9686):      (root) at <MyConverter>:5
04-24 09:42:10.863: W/System.err(9686): -------JRuby source-----------
04-24 09:42:10.863: W/System.err(9686): #encoding:utf-8
04-24 09:42:10.863: W/System.err(9686): #more JRuby, http://github.com/jruby/jruby/wiki
04-24 09:42:10.863: W/System.err(9686): #more Ruby, please read book "Programming Ruby"
04-24 09:42:10.863: W/System.err(9686): require 'java'
04-24 09:42:10.863: W/System.err(9686): import Java::hc.server.msb.Message
04-24 09:42:10.863: W/System.err(9686): class MyConverter < Java::hc.server.msb.Converter
```
it throws on ruboto_core_1_0_5.apk,
the apk is loaded by DexClassLoader.

other option information is done for ruboto as follow : 
1. System.setProperty("jruby.ji.proxyClassFactory", "org.ruboto.DalvikProxyClassFactory");
2. System.setProperty("jruby.class.cache.path", proxyCache.getAbsolutePath());
3. container.setCompatVersion(org.jruby.CompatVersion.RUBY2_0);
4. container.setCompileMode(org.jruby.RubyInstanceConfig$CompileMode.JIT);

**Comment by javalovercn** [comment]
change CompatVersion.RUBY2_0 to CompatVersion.RUBY1_8
it works well now.

**Comment by donv** [comment]
@javalovercn Well done!
