### ISSUE TITLE
Ruboto Core app crashes on Android Nougat

### ISSUE THREAD

**Issue by moxi** [ruboto/ruboto#810]
When I open the Ruboto Core app on Android 7 the app crashes, Here I'm the logcat message:

```
10-13 20:55:41.303 985-3865/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.ruboto.core/.RubotoCoreActivity (has extras)} from uid 10029 on display 0
10-13 20:55:41.421 985-3860/? I/ActivityManager: Start proc 17602:org.ruboto.core/u0a348 for activity org.ruboto.core/.RubotoCoreActivity
10-13 20:55:41.489 17602-17602/? W/System: ClassLoader referenced unknown path: /data/app/org.ruboto.core-1/lib/arm64
10-13 20:55:41.609 17602-17602/? D/RUBOTO: EntryPointActivity onCreate:
10-13 20:55:41.616 985-20335/? I/ActivityManager: START u0 {cmp=org.ruboto.core/org.ruboto.SplashActivity (has extras)} from uid 10348 on display 0
10-13 20:55:41.628 17602-17602/? I/System.out: RubotoActivity onCreate(): org.ruboto.core.RubotoCoreActivity, finishing: true
10-13 20:55:41.660 17602-17602/? D/RUBOTO: SplashActivity onCreate:
10-13 20:55:41.662 17602-17602/? I/RUBOTO: SplashActivity Showing progress
10-13 20:55:41.719 17602-17617/? D/RUBOTO: Max memory: 512MB
10-13 20:55:41.720 17602-17617/? D/RUBOTO: Setting up JRuby runtime (RELEASE)
10-13 20:55:41.725 17602-17602/? D/RUBOTO: SplashActivity onResume: 
10-13 20:55:41.737 17602-17617/? D/DexDex: validateClassPath : []
10-13 20:55:41.738 17602-17617/? D/DexDex: APK Date : 1476144590000 ,dexDir date : 1476144598000
10-13 20:55:41.738 17602-17617/? D/DexDex: shouldDexOpt(/data/app/org.ruboto.core-1/base.apk,/data/user/0/org.ruboto.core/app_dexdex,[]) => false on Thread[Thread-2,5,main]
                                           
                                           --------- beginning of crash
10-13 20:55:41.744 17602-17617/? E/AndroidRuntime: FATAL EXCEPTION: Thread-2
                                                   Process: org.ruboto.core, PID: 17602
                                                   java.lang.RuntimeException: java.lang.NoSuchMethodException: makeDexElements [class java.util.ArrayList, class java.io.File, class java.util.ArrayList]
                                                       at org.ruboto.DexDex.appendOdexesToClassPath(DexDex.java:271)
                                                       at org.ruboto.DexDex.validateClassPath(DexDex.java:158)
                                                       at org.ruboto.JRubyAdapter.setUpJRuby(JRubyAdapter.java:166)
                                                       at org.ruboto.JRubyAdapter.setUpJRuby(JRubyAdapter.java:123)
                                                       at org.ruboto.SplashActivity$1.run(SplashActivity.java:78)
                                                       at java.lang.Thread.run(Thread.java:761)
                                                    Caused by: java.lang.NoSuchMethodException: makeDexElements [class java.util.ArrayList, class java.io.File, class java.util.ArrayList]
                                                       at java.lang.Class.getMethod(Class.java:1981)
                                                       at java.lang.Class.getDeclaredMethod(Class.java:1960)
                                                       at org.ruboto.FrameworkHack.appendDexListImplICS(FrameworkHack.java:145)
                                                       at org.ruboto.DexDex.appendOdexesToClassPath(DexDex.java:260)
                                                       at org.ruboto.DexDex.validateClassPath(DexDex.java:158) 
                                                       at org.ruboto.JRubyAdapter.setUpJRuby(JRubyAdapter.java:166) 
                                                       at org.ruboto.JRubyAdapter.setUpJRuby(JRubyAdapter.java:123) 
                                                       at org.ruboto.SplashActivity$1.run(SplashActivity.java:78) 
                                                       at java.lang.Thread.run(Thread.java:761) 
10-13 20:55:41.755 985-4922/? W/ActivityManager:   Force finishing activity org.ruboto.core/org.ruboto.SplashActivity
10-13 20:55:41.762 17602-17616/? I/Adreno: QUALCOMM build                   : 74df444, I409c65498b
                                           Build Date                       : 06/22/16
                                           OpenGL ES Shader Compiler Version: XE031.08.00.02
                                           Local Branch                     : N16
                                           Remote Branch                    : 
                                           Remote Branch                    : 
                                           Reconstruct Branch               : 
10-13 20:55:41.773 17602-17616/? I/OpenGLRenderer: Initialized EGL, version 1.4
10-13 20:55:41.773 17602-17616/? D/OpenGLRenderer: Swap behavior 1
10-13 20:55:41.798 985-4918/? W/BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.amazon.mShop.android/com.amazon.mcc.crashreporter.android.CrashReportBroadcastReceiver requires android.permission.READ_LOGS due to sender android (uid 1000)
10-13 20:55:41.819 985-3551/? I/OpenGLRenderer: Initialized EGL, version 1.4
10-13 20:55:41.819 985-3551/? D/OpenGLRenderer: Swap behavior 1
10-13 20:55:41.985 17602-17602/? D/RUBOTO: SplashActivity onPause: 
10-13 20:55:42.019 985-3868/? I/WindowManager: Failed to capture screenshot of Token{3b02c36 ActivityRecord{94a9d1 u0 org.ruboto.core/org.ruboto.SplashActivity t1009 f}} appWin=Window{5715b1a u0 org.ruboto.core/org.ruboto.SplashActivity} drawState=4
10-13 20:55:42.210 985-4887/? I/ActivityManager: Process com.appspot.swisscodemonkeys.detector (pid 16896) has died
10-13 20:55:42.210 985-4887/? D/ActivityManager: cleanUpApplicationRecord -- 16896
10-13 20:55:42.215 985-4923/? I/ActivityManager: Process com.google.android.wearable.app:flow (pid 5074) has died
10-13 20:55:42.215 985-4923/? D/ActivityManager: cleanUpApplicationRecord -- 5074
10-13 20:55:42.215 985-4923/? W/ActivityManager: Scheduling restart of crashed service com.google.android.wearable.app/com.google.android.clockwork.companion.flow.FlowService in 1000ms
10-13 20:55:42.225 985-20333/? I/ActivityManager: Process com.qualcomm.qcrilmsgtunnel (pid 7944) has died
10-13 20:55:42.225 985-20333/? D/ActivityManager: cleanUpApplicationRecord -- 7944
10-13 20:55:42.225 985-20333/? W/ActivityManager: Scheduling restart of crashed service com.qualcomm.qcrilmsgtunnel/.QcrilMsgTunnelService in 10990ms
10-13 20:55:42.228 985-4921/? I/ActivityManager: Process com.android.documentsui (pid 17097) has died
10-13 20:55:42.228 985-4921/? D/ActivityManager: cleanUpApplicationRecord -- 17097
10-13 20:55:42.229 985-4924/? I/ActivityManager: Process com.android.musicfx (pid 16956) has died
10-13 20:55:42.229 985-4924/? D/ActivityManager: cleanUpApplicationRecord -- 16956
10-13 20:55:42.238 985-1410/? I/WindowManager: Destroying surface Surface(name=com.google.android.googlequicksearchbox/com.google.android.launcher.GEL) called by com.android.server.wm.WindowStateAnimator.destroyDeferredSurfaceLocked:910 com.android.server.wm.WindowStateAnimator.destroyPreservedSurfaceLocked:662 com.android.server.wm.WindowManagerService.destroyPreservedSurfaceLocked:8648 com.android.server.wm.WindowAnimator.animateLocked:792 com.android.server.wm.WindowAnimator.-wrap0:-1 com.android.server.wm.WindowAnimator$1.doFrame:140 android.view.Choreographer$CallbackRecord.run:869 android.view.Choreographer.doCallbacks:683 
10-13 20:55:42.245 985-3860/? I/ActivityManager: Process com.marriott.mrt (pid 6552) has died
10-13 20:55:42.245 985-3860/? D/ActivityManager: cleanUpApplicationRecord -- 6552
10-13 20:55:42.246 985-3860/? W/ActivityManager: Scheduling restart of crashed service com.marriott.mrt/com.marriott.mobile.network.gimbal.ProximityService in 20970ms
10-13 20:55:42.246 985-3860/? W/ActivityManager: Scheduling restart of crashed service com.marriott.mrt/com.gimbal.internal.service.GimbalService in 30969ms
10-13 20:55:42.275 985-4924/? I/ActivityManager: Process com.huawei.sarcontrolservice (pid 7921) has died
10-13 20:55:42.275 985-4924/? D/ActivityManager: cleanUpApplicationRecord -- 7921
10-13 20:55:42.275 985-4924/? W/ActivityManager: Scheduling restart of crashed service com.huawei.sarcontrolservice/.SarControlService in 40940ms
10-13 20:55:42.314 985-3865/? I/ActivityManager: Process com.google.android.apps.docs (pid 17018) has died
10-13 20:55:42.314 985-3865/? D/ActivityManager: cleanUpApplicationRecord -- 17018
10-13 20:55:42.357 17602-17602/? D/RUBOTO: SplashActivity onDestroy: 
10-13 20:55:42.388 17602-17602/? E/WindowManager: android.view.WindowLeaked: Activity org.ruboto.SplashActivity has leaked window DecorView@fc7e485[] that was originally added here
                                                      at android.view.ViewRootImpl.<init>(ViewRootImpl.java:417)
                                                      at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:331)
                                                      at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                      at android.app.Dialog.show(Dialog.java:316)
                                                      at android.app.ProgressDialog.show(ProgressDialog.java:116)
                                                      at android.app.ProgressDialog.show(ProgressDialog.java:104)
                                                      at org.ruboto.SplashActivity.showProgress(SplashActivity.java:171)
                                                      at org.ruboto.SplashActivity.initJRuby(SplashActivity.java:75)
                                                      at org.ruboto.SplashActivity.onCreate(SplashActivity.java:43)
                                                      at android.app.Activity.performCreate(Activity.java:6664)
                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                                                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                      at android.os.Looper.loop(Looper.java:154)
                                                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
10-13 20:55:42.390 985-20334/? I/WindowManager: Destroying surface Surface(name=org.ruboto.core/org.ruboto.SplashActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.removeLocked:1449 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2478 com.android.server.wm.WindowManagerService.removeWindowLocked:2436 com.android.server.wm.WindowManagerService.removeWindowLocked:2305 com.android.server.wm.WindowManagerService.removeWindow:2300 com.android.server.wm.Session.remove:193 
10-13 20:55:42.501 985-1410/? I/WindowManager: Destroying surface Surface(name=Starting org.ruboto.core) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.AppWindowAnimator.stepAnimationLocked:427 com.android.server.wm.WindowAnimator.updateAppWindowsLocked:196 com.android.server.wm.WindowAnimator.animateLocked:678 
10-13 20:55:42.507 985-1410/? I/WindowManager: Destroying surface Surface(name=org.ruboto.core/org.ruboto.SplashActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.WindowStateAnimator.finishExit:565 com.android.server.wm.WindowStateAnimator.stepAnimationLocked:491 com.android.server.wm.WindowAnimator.updateWindowsLocked:303 com.android.server.wm.WindowAnimator.animateLocked:704 
10-13 20:55:42.686 985-20335/? I/ActivityManager: Process com.android.vending (pid 16973) has died
10-13 20:55:42.686 985-20335/? D/ActivityManager: cleanUpApplicationRecord -- 16973
```

**Comment by Lukyczk** [comment]
I can second this

**Comment by donv** [comment]
Thanks for the report.  I'll try to get to this soon.

**Comment by donv** [comment]
Closing this issue since it relates to Ruboto 1.x.  Ruboto 2 now uses Android Studio with a much simpler setup.  A guide to getting started is in the README.
