### ISSUE TITLE
Package installer error

### ISSUE THREAD

**Issue by arjunmenon** [ruboto/ruboto#811]
```
~$ ruboto setup -y
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Not found
Android Emulator         : Not found
Android SDK Command adb  : Not found
Android SDK Command dx   : Not found
Platform SDK android-16  : Not found

    !!! Ruboto setup is NOT OK !!!

Android package installer not found.
F, [2016-11-09T23:07:09.282690 #5140] FATAL -- : undefined method `[]' for nil:NilClass (NoMethodError)
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruboto-1.4.1/lib/ruboto/util/setup.rb:153:in `get_android_sdk_version'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruboto-1.4.1/lib/ruboto/util/setup.rb:533:in `block in install_android_sdk'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruboto-1.4.1/lib/ruboto/util/setup.rb:525:in `chdir'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruboto-1.4.1/lib/ruboto/util/setup.rb:525:in `install_android_sdk'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruboto-1.4.1/lib/ruboto/util/setup.rb:306:in `install_all'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruboto-1.4.1/lib/ruboto/util/setup.rb:24:in `setup_ruboto'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruboto-1.4.1/lib/ruboto/commands/base.rb:467:in `run'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `block in run'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `catch'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `run'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruboto-1.4.1/lib/ruboto/commands/base.rb:28:in `main'
/home/arjun/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/ruboto-1.4.1/bin/ruboto:11:in `<top (required)>'
/home/arjun/.rbenv/versions/2.2.3/bin/ruboto:23:in `load'
/home/arjun/.rbenv/versions/2.2.3/bin/ruboto:23:in `<main>'

```
Have already setup Android Studio.

**Comment by donv** [comment]
Hi @arjunmenon !

Thanks for the report.  I'll have a look.

**Comment by donv** [comment]
Hi @arjunmenon !

I am working on this now.  Could you try with the new Ruboto 1.5.0 release?

**Comment by arjunmenon** [comment]
On first run
```
~/rails/betty$ ruboto setup -y
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Not found
Android Emulator         : Not found
Android SDK Command adb  : Not found
Android SDK Command dx   : Not found
Platform SDK android-16  : Not found

    !!! Ruboto setup is NOT OK !!!

Android package installer not found.
Android Package Installer: Foundlinux.tgz: 311MB/311MB 100%
Setting the ANDROID_HOME environment variable to /home/arjun/android-sdk-linux
Android tools not found.
Error: Argument 'build-tools_r23.0.1-windows.zip],extra-intel-Hardware_Accelerated_Execution_Manager,platform-tool,tool' is not recognized.

       Usage:
       android [global options] update sdk [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                     Action "update sdk":
  Updates the SDK by suggesting new platforms to install if available.
Options:
  -f --force     : Forces replacement of a package or its parts, even if
                   something has been modified.
  -n --dry-mode  : Simulates the update but does not download or install
                   anything.
     --proxy-host: HTTP/HTTPS proxy host (overrides settings if defined)
  -s --no-https  : Uses HTTP instead of HTTPS (the default) for downloads.
  -t --filter    : A filter that limits the update to the specified types of
                   packages in the form of a comma-separated list of
                   [platform, system-image, tool, platform-tool, doc, sample,
                   source]. This also accepts the identifiers returned by
                   'list sdk --extended'.
  -u --no-ui     : Updates from command-line (does not display the GUI)
     --proxy-port: HTTP/HTTPS proxy port (overrides settings if defined)
  -p --obsolete  : Deprecated. Please use --all instead.
  -a --all       : Includes all packages (such as obsolete and non-dependent
                   ones.)
Android SDK Command dx   : Not found
Android SDK Command adb  : Not found
Android Emulator         : Found
Android platform SDK for android-16 not found.
Refresh Sources:
  Fetching https://dl.google.com/android/repository/addons_list-2.xml
  Validate XML
  Parse XML
  Fetched Add-ons List successfully
  Refresh Sources
  Fetching URL: https://dl.google.com/android/repository/repository-11.xml
  Validate XML: https://dl.google.com/android/repository/repository-11.xml
  Parse XML:    https://dl.google.com/android/repository/repository-11.xml
  Fetching URL: https://dl.google.com/android/repository/addon.xml
  Validate XML: https://dl.google.com/android/repository/addon.xml
  Parse XML:    https://dl.google.com/android/repository/addon.xml
  Fetching URL: https://dl.google.com/android/repository/glass/addon.xml
  Validate XML: https://dl.google.com/android/repository/glass/addon.xml
  Parse XML:    https://dl.google.com/android/repository/glass/addon.xml
  Fetching URL: https://dl.google.com/android/repository/extras/intel/addon.xml
  Validate XML: https://dl.google.com/android/repository/extras/intel/addon.xml
  Parse XML:    https://dl.google.com/android/repository/extras/intel/addon.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android/sys-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android-wear/sys-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/android-tv/sys-img.xml
  Fetching URL: https://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Validate XML: https://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml
  Parse XML:    https://dl.google.com/android/repository/sys-img/google_apis/sys-img.xml
Error: Ignoring unknown package filter 'sys-img-x86_64-android-16'
-------------------------------
License id: android-sdk-license-c81a61d9
Used by: 
 - SDK Platform Android 4.1.2, API 16, revision 5
  - ARM EABI v7a System Image, Android API 16, revision 4
  - Intel x86 Atom System Image, Android API 16, revision 5
-------------------------------

Terms and Conditions

This is the Android Software Development Kit License Agreement
...
...

November 20, 2015
Do you accept the license 'android-sdk-license-c81a61d9' [y/n]: 
Installing Archives:
  Preparing to install archives
  Downloading SDK Platform Android 4.1.2, API 16, revision 5
  Installing SDK Platform Android 4.1.2, API 16, revision 5
    Installed SDK Platform Android 4.1.2, API 16, revision 596%)
  Downloading ARM EABI v7a System Image, Android API 16, revision 4
  Installing ARM EABI v7a System Image, Android API 16, revision 4
    Installed ARM EABI v7a System Image, Android API 16, revision 499%)
  Downloading Intel x86 Atom System Image, Android API 16, revision 5
  Installing Intel x86 Atom System Image, Android API 16, revision 5
    Installed Intel x86 Atom System Image, Android API 16, revision 599%)
  Done. 3 packages installed.
Platform SDK android-16  : Found
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Android SDK Command adb  : Not found
Android SDK Command dx   : Not found
Platform SDK android-16  : Found

    !!! Ruboto setup is NOT OK !!!


You are missing some paths.  Execute these lines to add them:

    export PATH="/home/arjun/android-sdk-linux/tools:$PATH"

Updated /home/arjun/.bashrc to load the ~/.rubotorc config file.
Please close your command window and reopen, or run

    source ~/.rubotorc
```

I ran those two commands and then,
On second run
```
~/rails/betty$ ruboto setup -y
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Android SDK Command adb  : Not found
Android SDK Command dx   : Not found
Platform SDK android-16  : Found

    !!! Ruboto setup is NOT OK !!!

Android tools not found.
Error: Argument 'build-tools_r23.0.1-windows.zip],extra-intel-Hardware_Accelerated_Execution_Manager,platform-tool,tool' is not recognized.

       Usage:
       android [global options] update sdk [action options]
       Global options:
  -s --silent     : Silent mode, shows errors only.
  -v --verbose    : Verbose mode, shows errors, warnings and all messages.
     --clear-cache: Clear the SDK Manager repository manifest cache.
  -h --help       : Help on a specific command.

                     Action "update sdk":
  Updates the SDK by suggesting new platforms to install if available.
Options:
  -f --force     : Forces replacement of a package or its parts, even if
                   something has been modified.
  -n --dry-mode  : Simulates the update but does not download or install
                   anything.
     --proxy-host: HTTP/HTTPS proxy host (overrides settings if defined)
  -s --no-https  : Uses HTTP instead of HTTPS (the default) for downloads.
  -t --filter    : A filter that limits the update to the specified types of
                   packages in the form of a comma-separated list of
                   [platform, system-image, tool, platform-tool, doc, sample,
                   source]. This also accepts the identifiers returned by
                   'list sdk --extended'.
  -u --no-ui     : Updates from command-line (does not display the GUI)
     --proxy-port: HTTP/HTTPS proxy port (overrides settings if defined)
  -p --obsolete  : Deprecated. Please use --all instead.
  -a --all       : Includes all packages (such as obsolete and non-dependent
                   ones.)
Android SDK Command dx   : Not found
Android SDK Command adb  : Not found
Android Emulator         : Found
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Found
Android Emulator         : Found
Android SDK Command adb  : Not found
Android SDK Command dx   : Not found
Platform SDK android-16  : Found

    !!! Ruboto setup is NOT OK !!!
```

On thing I do not understand is, even though previously I had installed Android Studio, then is it supposed to reinstall more Android packages?

**Comment by donv** [comment]
Hi @arjunmenon !

Thanks for the feedback.  There are two errors, and I'll fix both:

* The Android Studio tools should be detected
* The tool installation should work

I'll fix both as soon as I can.

**Comment by arjunmenon** [comment]
Heya
Any updates?

**Comment by donv** [comment]
Hi @arjunmenon !

The tools installation is fixed on master.

Detection of Android Studio i spending.

Contributions welcome 😄 .

**Comment by mvdamme** [comment]
It seems like the Android SDK download pages have changed, I now get the following (both under 1.5.0 and when using master) when I run `ruboto setup -y`:

```
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Not found
Android Emulator         : Not found
Android SDK Command adb  : Not found
Android SDK Command dx   : Not found
Platform SDK android-16  : Not found

    !!! Ruboto setup is NOT OK !!!

Android package installer not found.
F, [2016-12-08T22:49:59.206164 #1943] FATAL -- : undefined method `[]' for nil:NilClass (NoMethodError)
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:157:in `get_android_sdk_version'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:537:in `block in install_android_sdk'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:529:in `chdir'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:529:in `install_android_sdk'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:310:in `install_all'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:24:in `setup_ruboto'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/ruboto-1.5.0/lib/ruboto/commands/base.rb:467:in `run'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `block in run'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `catch'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `run'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/ruboto-1.5.0/lib/ruboto/commands/base.rb:28:in `main'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/gems/ruboto-1.5.0/bin/ruboto:11:in `<top (required)>'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/bin/ruboto:23:in `load'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/bin/ruboto:23:in `<main>'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/bin/ruby_executable_hooks:15:in `eval'
/home/michael/.rvm/gems/ruby-2.2.4@ruboto/bin/ruby_executable_hooks:15:in `<main>'
```
Essentially, the regex that looks for the SDK download link doesn't return any results.

**Comment by donv** [comment]
Looking at this now.

**Comment by donv** [comment]
This should be OK now.  Please test and report back.

**Comment by mvdamme** [comment]
It works perfecly now, thanks!

**Comment by donv** [comment]
Thanks for verifying! 😄
