### ISSUE TITLE
ArgumentError creating new emulator image (AVD)

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#813]
```
Creating AVD Android_4.4.2
Created AVD 'Android_4.4.2' based on Android 4.4.2, ARM (armeabi-v7a) processor,
with the following hardware config:
hw.accelerometer=yes
hw.audioInput=yes
hw.battery=yes
hw.dPad=no
hw.device.hash2=MD5:36362a51e6c830c2ab515a312c9ecbff
hw.device.manufacturer=Google
hw.device.name=Nexus One
hw.gps=yes
hw.keyboard=no
hw.lcd.density=240
hw.mainKeys=yes
hw.sdCard=yes
hw.sensors.orientation=no
hw.sensors.proximity=yes
hw.trackBall=yes
F, [2016-11-17T11:47:05.073926 #4901] FATAL -- : wrong number of arguments (given 2, expected 3) (ArgumentError)
/home/travis/.rvm/gems/ruby-2.3.1/gems/ruboto-1.5.0/lib/ruboto/util/emulator.rb:268:in `patch_config_ini'
/home/travis/.rvm/gems/ruby-2.3.1/gems/ruboto-1.5.0/lib/ruboto/util/emulator.rb:250:in `create_avd'
/home/travis/.rvm/gems/ruby-2.3.1/gems/ruboto-1.5.0/lib/ruboto/util/emulator.rb:102:in `block in start_emulator'
/home/travis/.rvm/gems/ruby-2.3.1/gems/ruboto-1.5.0/lib/ruboto/util/emulator.rb:62:in `loop'
/home/travis/.rvm/gems/ruby-2.3.1/gems/ruboto-1.5.0/lib/ruboto/util/emulator.rb:62:in `start_emulator'
/home/travis/.rvm/gems/ruby-2.3.1/gems/ruboto-1.5.0/lib/ruboto/commands/base.rb:494:in `run'
/home/travis/.rvm/gems/ruby-2.3.1/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `block in run'
/home/travis/.rvm/gems/ruby-2.3.1/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `catch'
/home/travis/.rvm/gems/ruby-2.3.1/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `run'
/home/travis/.rvm/gems/ruby-2.3.1/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/home/travis/.rvm/gems/ruby-2.3.1/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/home/travis/.rvm/gems/ruby-2.3.1/gems/ruboto-1.5.0/lib/ruboto/commands/base.rb:28:in `main'
/home/travis/.rvm/gems/ruby-2.3.1/gems/ruboto-1.5.0/bin/ruboto:11:in `<top (required)>'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruboto:23:in `load'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruboto:23:in `<main>'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by donv** [comment]
Fixed in 1.5.1.
