### ISSUE TITLE
Error when creating a new emulator image for an app with empty ruboto.yml

### ISSUE THREAD

**Issue by donv** [ruboto/ruboto#818]
```
Creating AVD Android_4.0.3
Available abis: ["default/armeabi-v7a", "default/x86"]
F, [2016-11-17T23:05:16.981928 #57969] FATAL -- : undefined method `[]' for false:FalseClass (NoMethodError)
/Users/uwe/.gem/ruby/2.3.1/gems/ruboto-1.5.1.dev/lib/ruboto/util/emulator.rb:236:in `create_avd'
/Users/uwe/.gem/ruby/2.3.1/gems/ruboto-1.5.1.dev/lib/ruboto/util/emulator.rb:102:in `block in start_emulator'
/Users/uwe/.gem/ruby/2.3.1/gems/ruboto-1.5.1.dev/lib/ruboto/util/emulator.rb:62:in `loop'
/Users/uwe/.gem/ruby/2.3.1/gems/ruboto-1.5.1.dev/lib/ruboto/util/emulator.rb:62:in `start_emulator'
/Users/uwe/.gem/ruby/2.3.1/gems/ruboto-1.5.1.dev/lib/ruboto/commands/base.rb:494:in `run'
/Users/uwe/.gem/ruby/2.3.1/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `block in run'
/Users/uwe/.gem/ruby/2.3.1/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `catch'
/Users/uwe/.gem/ruby/2.3.1/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `run'
/Users/uwe/.gem/ruby/2.3.1/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/Users/uwe/.gem/ruby/2.3.1/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/Users/uwe/.gem/ruby/2.3.1/gems/ruboto-1.5.1.dev/lib/ruboto/commands/base.rb:28:in `main'
/Users/uwe/.gem/ruby/2.3.1/gems/ruboto-1.5.1.dev/bin/ruboto:11:in `<top (required)>'
/Users/uwe/.gem/ruby/2.3.1/bin/ruboto:23:in `load'
/Users/uwe/.gem/ruby/2.3.1/bin/ruboto:23:in `<main>'
```

**Comment by donv** [comment]
The empty yaml file is read as "false" instead of a hash.
