### ISSUE TITLE
undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by at-longhoang** [ruboto/ruboto#824]
OS: Ubuntu 16.04 LTS
I ran 
```
ruboto setup -y
```
I got an errors
```
WARN: Unresolved specs during Gem::Specification.reset:
      rubyzip (~> 1.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Java runtime             : Found
Java Compiler            : Found
Apache ANT               : Found
Android Package Installer: Not found
Android Emulator         : Not found
Android SDK Command adb  : Not found
Android SDK Command dx   : Not found
Platform SDK android-16  : Not found

    !!! Ruboto setup is NOT OK !!!

Android package installer not found.
F, [2016-12-17T09:27:58.133085 #15676] FATAL -- : undefined method `[]' for nil:NilClass (NoMethodError)
/home/longhp/.rvm/gems/ruby-2.2.3/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:157:in `get_android_sdk_version'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:537:in `block in install_android_sdk'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:529:in `chdir'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:529:in `install_android_sdk'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:310:in `install_all'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/ruboto-1.5.0/lib/ruboto/util/setup.rb:24:in `setup_ruboto'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/ruboto-1.5.0/lib/ruboto/commands/base.rb:467:in `run'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/main-5.3.2/lib/main/program/class_methods.rb:155:in `block in run'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `catch'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/main-5.3.2/lib/main/program/class_methods.rb:144:in `run'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/main-5.3.2/lib/main/factories.rb:18:in `run'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/main-5.3.2/lib/main/factories.rb:25:in `Main'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/ruboto-1.5.0/lib/ruboto/commands/base.rb:28:in `main'
/home/longhp/.rvm/gems/ruby-2.2.3/gems/ruboto-1.5.0/bin/ruboto:11:in `<top (required)>'
/home/longhp/.rvm/gems/ruby-2.2.3/bin/ruboto:23:in `load'
/home/longhp/.rvm/gems/ruby-2.2.3/bin/ruboto:23:in `<main>'
/home/longhp/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
/home/longhp/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by monochrome-particles** [comment]
Hi there,
Do you have an Android SDK installed on your machine?

**Comment by donv** [comment]
Looking at this now.

**Comment by donv** [comment]
This should be OK now.  Please test and report back.

**Comment by nathanmp** [comment]
I have the same problem as of May 2nd.

**Comment by donv** [comment]
@nathanmp Are you using Ruboto 1.6.1?

**Comment by nathanmp** [comment]
@donv I have a different error, actually. I'll open a new issue for it.
